# Generated by Django 3.1.2 on 2020-10-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0003_userprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_for_name', models.CharField(max_length=30)),
                ('sent_for_relation_with_sender', models.CharField(max_length=50)),
                ('sent_for_bgrp', models.CharField(max_length=3)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('accepted_by_sender', models.BooleanField(default=False)),
                ('accepted_by_reciever', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_received', to='userauth.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sent', to='userauth.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_on', models.DateField()),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='s_donation', to='search.donationrequest')),
            ],
        ),
    ]
