# Generated by Django 3.1.2 on 2020-11-19 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_on', models.DateField(null=True)),
                ('donated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_history', to='userauth.userprofile')),
                ('donated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acception_history', to='userauth.userprofile')),
            ],
            options={
                'ordering': ['-donated_on'],
            },
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_received', to='userauth.userprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_sent', to='userauth.userprofile')),
            ],
            options={
                'ordering': ['-time_sent'],
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
