# Generated by Django 3.1.2 on 2020-10-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_userprofile_age'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationhistory',
            options={'ordering': ['-donated_on']},
        ),
        migrations.AlterModelOptions(
            name='donationrequest',
            options={'ordering': ['-time_sent']},
        ),
        migrations.RenameField(
            model_name='donationrequest',
            old_name='accepted_by_reciever',
            new_name='accepted',
        ),
        migrations.RemoveField(
            model_name='donationhistory',
            name='donation',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='accepted_by_sender',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='sent_for_bgrp',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='sent_for_name',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='sent_for_relation_with_sender',
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='donated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donation_history', to='userauth.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationhistory',
            name='donated_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='acception_history', to='userauth.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
