# Generated by Django 3.1.2 on 2020-10-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20201017_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
